#!/bin/sh

rm -rf build/ CMakeCache.txt CMakeFiles/ cmake_install.cmake Makefile build.ninja rules.ninja *.xcodeproj *.build CMakeScripts

if [ -d "AlloSystem" ]; then
    cd AlloSystem
    ./distclean
    cd ..
fi

if [ -d "GLV" ]; then
    cd GLV
    ./distclean
    cd ..
fi

if [ -d "Gamma" ]; then
    cd Gamma
    ./distclean
    cd ..
fi

if [ -d "vsr" ]; then
    cd vsr
    ./distclean
    cd ..
fi
